### ISSUE TITLE
Добавьте описания ошибок и сообщения для плательщика

### ISSUE THREAD

**Issue by un1t** [antidasoftware/cloudpayments-python-client#1]
Добрый день.

Хотелось бы показывать плательщику человеческую ошибку, как описано на странице https://cloudpayments.ru/Docs/Directory

Будет круто, если добавите.

Спасибо.

**Comment by rodionovstepan** [comment]
@un1t привет!

Спасибо за замечание. В ближайшее время добавим.

Удачи.

**Comment by igor-shevchenko** [comment]
У `PaymentError` уже было свойство `cardholder_message`, в котором хранилось сообщение для плательщика, пришедшее от сервера. Оно не всегда совпадает с сообщением из документации, поэтому дополнительно добавили еще два свойства: `verbose_reason` и `verbose_message`, в них находятся описания ошибок из документации. Используйте сообщения, которые будут удобнее.
