### ISSUE TITLE
Дата передается без указания таймзоны

### ISSUE THREAD

**Issue by schibrikov** [antidasoftware/cloudpayments-python-client#18]
Привет
мы используем вашу библиотеку и поймали проблему - при пересоздании подписки (создаем новую и копируем в StartDate дату следующего платежа) эта дата двигается на 3 часа назад.

Я покопался и обнаружил что вот [здесь](https://github.com/antidasoftware/cloudpayments-python-client/blob/master/cloudpayments/utils.py#L16) дата форматируется без указания таймзоны.

Возможно проблема происходит из-за интерпретации сервером cloudpayments даты без таймзоны как даты в локальной таймзоне их сервера. На это указывает и смещение - 3 часа это как раз разница между UTC и Москвой.
У себя в примере они указывают дату как `2014-08-06T16:46:29.5377246Z`, где Z указывает на время по UTC.

Я сейчас проверяю эту теорию, но вероятно это так.
Предлагаю добавить Z к формату даты, могу сделать ПР.

**Comment by schibrikov** [comment]
Я проверил - проблема точно возникает по описанным причинам.
После применения изменений аналогичных ПР проблема исчезла, подписка создается с корректной датой.

**Comment by schibrikov** [comment]
@rodionovstepan @igor-shevchenko
Добрый день!
А когда теперь получится сделать релиз с этими изменениями?

**Comment by igor-shevchenko** [comment]
@schibrikov публикация пакетов на pypi отвалилась, попробуйте пока поставить с гитхаба:

```pip install git+git://github.com/antidasoftware/cloudpayments-python-client.git@1.6.4```

**Comment by schibrikov** [comment]
все работает, спасибо, закрываю ишью
