### ISSUE TITLE
Планируется ли добавить поддержку API онлайн касс?

### ISSUE THREAD

**Issue by un1t** [antidasoftware/cloudpayments-python-client#3]
Добрый день.

Хотелось бы увидеть поддержку API кассы (описано тут https://cloudpayments.ru/docs/api/kassa)

Если планируется то можно ли узнать в какие сроки?
(Если в течении недели, то еще есть есть смысл подождать. Если дольше, то видимо тогда проще выпилить библиотеку и обращаться напрямую к API.)

**Comment by rodionovstepan** [comment]
@un1t привет.

Планируется. В самые ближайшие сроки.

**Comment by igor-shevchenko** [comment]
@un1t добавили новый метод для формирования кассового чека. В ближайшие дни поправим #1 и #2 и зальем новую версию на PyPI.

Если метод нужен срочно, то можно [установить библиотеку c Гитхаба](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).

**Comment by igor-shevchenko** [comment]
@un1t залили на PyPI, теперь версию с поддержной API для чеков можно ставить через pip.
